// Package config loads runtime configuration from the environment.
package config

import (
	"fmt"
	"os"
	"time"

	"github.com/joho/godotenv"
)

type Config struct {
	// AuthToken is the static bearer token the ESP32 must send to be
	// served display data.
	AuthToken string
	Port      string

	// GoogleCredentialsFile is the path to the credentials file used to
	// read the reference calendar (authorized_user format, generated by
	// cmd/oauthsetup; option.WithCredentialsFile also accepts a service
	// account key, but personal GCP projects can't create those).
	GoogleCredentialsFile string
	// CalendarID is the fixed reference calendar to read events from.
	CalendarID string
	// GoogleSheetID is the fixed reference spreadsheet to read the
	// shopping list from (its first tab, one product per row from row 2
	// on). Uses the same GoogleCredentialsFile as the calendar.
	GoogleSheetID string
	// Location is the timezone used to compute "today" and to format
	// event times, parsed from the TZ environment variable.
	Location *time.Location
}

// Load reads configuration from the environment, loading a local .env
// file first if present (development only; in production the VPS sets
// real environment variables and no .env file exists).
func Load() (*Config, error) {
	_ = godotenv.Load()

	token := os.Getenv("AUTH_TOKEN")
	if token == "" {
		return nil, fmt.Errorf("config: AUTH_TOKEN environment variable is required")
	}

	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}

	credentialsFile := os.Getenv("GOOGLE_CREDENTIALS_FILE")
	if credentialsFile == "" {
		return nil, fmt.Errorf("config: GOOGLE_CREDENTIALS_FILE environment variable is required")
	}

	calendarID := os.Getenv("CALENDAR_ID")
	if calendarID == "" {
		return nil, fmt.Errorf("config: CALENDAR_ID environment variable is required")
	}

	sheetID := os.Getenv("GOOGLE_SHEET_ID")
	if sheetID == "" {
		return nil, fmt.Errorf("config: GOOGLE_SHEET_ID environment variable is required")
	}

	tz := os.Getenv("TZ")
	if tz == "" {
		return nil, fmt.Errorf("config: TZ environment variable is required")
	}
	loc, err := time.LoadLocation(tz)
	if err != nil {
		return nil, fmt.Errorf("config: invalid TZ %q: %w", tz, err)
	}

	return &Config{
		AuthToken:             token,
		Port:                  port,
		GoogleCredentialsFile: credentialsFile,
		CalendarID:            calendarID,
		GoogleSheetID:         sheetID,
		Location:              loc,
	}, nil
}
