package main

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/sha256"
	"crypto/tls"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"fmt"
	"math/big"
	"net"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
	"time"
)

func TestEnsureTLSCertGeneratesValidCertificate(t *testing.T) {
	dir := t.TempDir()
	certPath := filepath.Join(dir, "cert.pem")
	keyPath := filepath.Join(dir, "key.pem")

	fingerprint, certPEM, err := ensureTLSCert(certPath, keyPath)
	if err != nil {
		t.Fatalf("ensureTLSCert() error = %v", err)
	}

	pair, err := tls.LoadX509KeyPair(certPath, keyPath)
	if err != nil {
		t.Fatalf("loading generated key pair: %v", err)
	}
	leaf, err := x509.ParseCertificate(pair.Certificate[0])
	if err != nil {
		t.Fatalf("parsing generated certificate: %v", err)
	}

	if leaf.PublicKeyAlgorithm != x509.ECDSA {
		t.Errorf("PublicKeyAlgorithm = %v, want ECDSA", leaf.PublicKeyAlgorithm)
	}

	validity := leaf.NotAfter.Sub(leaf.NotBefore)
	if validity < 9*365*24*time.Hour || validity > 10*366*24*time.Hour {
		t.Errorf("validity = %v, want ~10 years", validity)
	}

	wantIPs := []net.IP{net.IPv4(127, 0, 0, 1), net.IPv6loopback}
	for _, want := range wantIPs {
		found := false
		for _, ip := range leaf.IPAddresses {
			if ip.Equal(want) {
				found = true
				break
			}
		}
		if !found {
			t.Errorf("IPAddresses = %v, want to contain %v", leaf.IPAddresses, want)
		}
	}

	foundLocalhost := false
	for _, name := range leaf.DNSNames {
		if name == "localhost" {
			foundLocalhost = true
		}
	}
	if !foundLocalhost {
		t.Errorf("DNSNames = %v, want to contain %q", leaf.DNSNames, "localhost")
	}

	fingerprintRe := regexp.MustCompile(`^([0-9A-F]{2}:){31}[0-9A-F]{2}$`)
	if !fingerprintRe.MatchString(fingerprint) {
		t.Errorf("fingerprint = %q, does not match expected format", fingerprint)
	}

	if !strings.Contains(certPEM, "-----BEGIN CERTIFICATE-----") {
		t.Errorf("certPEM does not contain a PEM certificate block: %q", certPEM)
	}
}

func TestEnsureTLSCertIsIdempotent(t *testing.T) {
	dir := t.TempDir()
	certPath := filepath.Join(dir, "cert.pem")
	keyPath := filepath.Join(dir, "key.pem")

	fingerprint1, certPEM1, err := ensureTLSCert(certPath, keyPath)
	if err != nil {
		t.Fatalf("first ensureTLSCert() error = %v", err)
	}
	keyBytes1, err := os.ReadFile(keyPath)
	if err != nil {
		t.Fatalf("reading key after first call: %v", err)
	}

	fingerprint2, certPEM2, err := ensureTLSCert(certPath, keyPath)
	if err != nil {
		t.Fatalf("second ensureTLSCert() error = %v", err)
	}
	keyBytes2, err := os.ReadFile(keyPath)
	if err != nil {
		t.Fatalf("reading key after second call: %v", err)
	}

	if fingerprint1 != fingerprint2 {
		t.Errorf("fingerprint changed across calls: %q != %q", fingerprint1, fingerprint2)
	}
	if certPEM1 != certPEM2 {
		t.Errorf("certPEM changed across calls")
	}
	if string(keyBytes1) != string(keyBytes2) {
		t.Errorf("key file bytes changed across calls; second call must not regenerate")
	}
}

// TestEnsureTLSCertReusesExternalCert proves ensureTLSCert doesn't
// require the cert/key pair to have been generated by this program —
// dropping in a real CA-issued (or any other) cert/key pair at the same
// paths and restarting is enough to switch away from the self-signed
// certificate, no code change needed.
func TestEnsureTLSCertReusesExternalCert(t *testing.T) {
	dir := t.TempDir()
	certPath := filepath.Join(dir, "cert.pem")
	keyPath := filepath.Join(dir, "key.pem")

	externalFingerprint, externalCertPEM, externalKeyPEM := generateUnrelatedCert(t)
	if err := os.WriteFile(certPath, []byte(externalCertPEM), 0o644); err != nil {
		t.Fatalf("writing external cert: %v", err)
	}
	if err := os.WriteFile(keyPath, []byte(externalKeyPEM), 0o600); err != nil {
		t.Fatalf("writing external key: %v", err)
	}

	fingerprint, certPEM, err := ensureTLSCert(certPath, keyPath)
	if err != nil {
		t.Fatalf("ensureTLSCert() error = %v", err)
	}

	if fingerprint != externalFingerprint {
		t.Errorf("fingerprint = %q, want the externally-provided cert's fingerprint %q (got a freshly generated one instead)", fingerprint, externalFingerprint)
	}
	if certPEM != externalCertPEM {
		t.Errorf("certPEM does not match the externally-provided cert (got a freshly generated one instead)")
	}
}

func TestEnsureTLSCertRegeneratesWhenOneFileMissing(t *testing.T) {
	dir := t.TempDir()
	certPath := filepath.Join(dir, "cert.pem")
	keyPath := filepath.Join(dir, "key.pem")

	if _, _, err := ensureTLSCert(certPath, keyPath); err != nil {
		t.Fatalf("initial ensureTLSCert() error = %v", err)
	}
	if err := os.Remove(keyPath); err != nil {
		t.Fatalf("removing key file: %v", err)
	}

	if _, _, err := ensureTLSCert(certPath, keyPath); err != nil {
		t.Fatalf("ensureTLSCert() after partial state error = %v", err)
	}

	if _, err := os.Stat(certPath); err != nil {
		t.Errorf("cert file missing after regeneration: %v", err)
	}
	if _, err := os.Stat(keyPath); err != nil {
		t.Errorf("key file missing after regeneration: %v", err)
	}
}

func TestFingerprintSHA256Format(t *testing.T) {
	input := []byte("fixed input")
	sum := sha256.Sum256(input)
	var want strings.Builder
	for i, b := range sum {
		if i > 0 {
			want.WriteByte(':')
		}
		want.WriteString(fmt.Sprintf("%02X", b))
	}

	got := fingerprintSHA256(input)
	if got != want.String() {
		t.Errorf("fingerprintSHA256() = %q, want %q", got, want.String())
	}
}

type fakeAddr struct{ s string }

func (f fakeAddr) Network() string { return "fake" }
func (f fakeAddr) String() string  { return f.s }

func TestLocalNonLoopbackIPsFiltersLoopbackAndLinkLocal(t *testing.T) {
	mustIPNet := func(cidr string) *net.IPNet {
		ip, ipNet, err := net.ParseCIDR(cidr)
		if err != nil {
			t.Fatalf("ParseCIDR(%q): %v", cidr, err)
		}
		ipNet.IP = ip
		return ipNet
	}

	addrs := []net.Addr{
		mustIPNet("127.0.0.1/8"),
		mustIPNet("::1/128"),
		mustIPNet("169.254.1.1/16"),
		mustIPNet("fe80::1/64"),
		mustIPNet("192.168.1.50/24"),
		mustIPNet("2001:db8::1/64"),
		fakeAddr{"not-an-ipnet"},
	}

	got := localNonLoopbackIPs(addrs)

	wantKept := []net.IP{net.ParseIP("192.168.1.50"), net.ParseIP("2001:db8::1")}
	if len(got) != len(wantKept) {
		t.Fatalf("localNonLoopbackIPs() = %v, want %v", got, wantKept)
	}
	for i, want := range wantKept {
		if !got[i].Equal(want) {
			t.Errorf("localNonLoopbackIPs()[%d] = %v, want %v", i, got[i], want)
		}
	}
}

// generateUnrelatedCert builds a self-signed cert/key pair with a
// distinct CommonName/serial/validity from generateSelfSignedCert's own
// shape, standing in for a certificate the user provided by hand (e.g.
// one issued by a real CA) rather than one this program generated.
func generateUnrelatedCert(t *testing.T) (fingerprint, certPEM, keyPEM string) {
	t.Helper()

	priv, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatalf("generating key: %v", err)
	}
	template := &x509.Certificate{
		SerialNumber: big.NewInt(12345),
		Subject:      pkix.Name{CommonName: "externally-provided-cert.example"},
		NotBefore:    time.Now(),
		NotAfter:     time.Now().AddDate(1, 0, 0),
		KeyUsage:     x509.KeyUsageDigitalSignature,
		ExtKeyUsage:  []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
		DNSNames:     []string{"example.com"},
	}

	der, err := x509.CreateCertificate(rand.Reader, template, template, &priv.PublicKey, priv)
	if err != nil {
		t.Fatalf("creating certificate: %v", err)
	}
	keyBytes, err := x509.MarshalPKCS8PrivateKey(priv)
	if err != nil {
		t.Fatalf("marshaling key: %v", err)
	}

	certPEMBytes := pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: der})
	keyPEMBytes := pem.EncodeToMemory(&pem.Block{Type: "PRIVATE KEY", Bytes: keyBytes})

	return fingerprintSHA256(der), string(certPEMBytes), string(keyPEMBytes)
}
